using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using Unity.VisualScripting;

public class PlaneController : MonoBehaviour
{
    [Header("Flying Obj Stats")]
    [Tooltip("How much the speed ramps up or down")]
    public float throttleIncriment = 0.1f;
    [Tooltip("Maximum speed of the object")]
    public float maxThrust = 200f;
    [Tooltip("How responsive the object is to directional movement")]
    public float responsiveness = 100f;
    [Tooltip("Lift generated by the object dependant on it's speed")]
    public float lift = 135f;
    [Header("UI")]
    [SerializeField] TextMeshProUGUI statsHud;
    [SerializeField] TextMeshProUGUI titleHud;
    [SerializeField] TextMeshProUGUI timerHUD;

    [Header("Game Over Menu")]
    [SerializeField] TextMeshProUGUI playerTime;
    [SerializeField] TextMeshProUGUI bestTime;
    [SerializeField] TextMeshProUGUI isWinnerText;
    [SerializeField] GameObject GameOverMenu;
    public AudioClip winnerMusic;

    [Header("Misc")]
    [SerializeField] Animator animator;
    [SerializeField] GameObject landingCollider;
    [SerializeField] Collider[] collArr;
    public GameObject altimeterObj;
    public float heave = 0;
    public LayerMask terrainLayer;
    public AudioClip[] flapAudio;
    public int maxEggs;

    private float throttle;
    private float yaw;
    private float pitch;
    private float roll;

    int currentAlt;
    int currentSpeed;
    int currentThrottle;

    float activeTimer = 0;
    System.TimeSpan rtime;
    System.TimeSpan timer;

    public int eggsCollected;

    float rollAmount;
    float pitchAmount;

    private float responseModifier
    {
        get
        {
            return (rb.mass / 10f) * responsiveness;
        }
    }

    AudioSource mainAud;
    public AudioSource secAud;
    Rigidbody rb;

    private void Awake()
    {
        Time.timeScale = 1;
        
        rtime = System.TimeSpan.FromSeconds(PlayerPrefs.GetFloat("BestTime", 12345.0f));
        mainAud = GetComponent<AudioSource>();
        rb = GetComponent<Rigidbody>();
        PlatformController.singleton.Init("COM3", 115200);
        LandingAnim();
    }

    private void InputHandling()
    {
        // Set Rotational values from out inputs
        if (Input.GetKeyDown(KeyCode.Joystick2Button4)) // Button 4
        {
            // Landing
            if (animator.GetBool("isFlying") && currentAlt <= 6 && currentThrottle == 0)
            {
                //transform.rotation = Quaternion.Euler(0, transform.eulerAngles.y, 0);
                //rb.constraints = RigidbodyConstraints.FreezeAll;
                LandingAnim();
            }
            // TakeOff
            else
            {
                TakeoffAnim();
            }
        }

        if (animator.GetBool("isFlying"))
        {
            throttle += throttleIncriment * Input.GetAxis("Throttle");
        }

        yaw = Input.GetAxis("Yaw");
        pitch = Input.GetAxis("Pitch");
        roll = Input.GetAxis("Roll");

        throttle = Mathf.Clamp(throttle, 0f, 100f);
    }

    private void Update()
    {

        if (Application.isEditor && Input.GetKeyDown(KeyCode.Backspace))
        {
            PlayerPrefs.DeleteKey("BestTime");
        }
        activeTimer += Time.deltaTime;
        InputHandling();
        UpdateHUD();
        rollAmount = Mathf.DeltaAngle(transform.eulerAngles.z, 0);
        pitchAmount = -Mathf.DeltaAngle(transform.eulerAngles.x, 0);
        PlatformController.singleton.Roll = PlatformController.singleton.MapRange(rollAmount, -45, 45, -10, 10);
        PlatformController.singleton.Pitch = PlatformController.singleton.MapRange(-pitchAmount, -55, 55, -10, 10);
        PlatformController.singleton.Heave = -heave;
    }

    private void FixedUpdate()
    {
        float rollAmount = Mathf.DeltaAngle(transform.eulerAngles.z, 0);
        float pitchAmount = -Mathf.DeltaAngle(transform.eulerAngles.x, 0);
        // Apply Forces
        
        if (animator.GetBool("isFlying"))
        {
            rb.AddForce(transform.forward * maxThrust * throttle);
            rb.AddTorque(transform.up * yaw * responsiveness);

            rb.AddTorque(transform.right * pitch * responsiveness);

            rb.AddTorque(-transform.forward * roll * responsiveness);

            rb.AddForce(Vector3.up * rb.velocity.magnitude * lift);
        }
    }

    private void UpdateHUD()
    {
        currentThrottle = (int)throttle;
        currentSpeed = (int)(rb.velocity.magnitude * 3.6f);
        RaycastHit hit;
        if (Physics.Raycast(transform.position, Vector3.down, out hit, Mathf.Infinity, terrainLayer))
        {
            currentAlt = (int)(altimeterObj.transform.position - hit.point).magnitude;
        }

        statsHud.text = "Throttle: " + currentThrottle + "\n";
        statsHud.text += "Airspeed: " + currentSpeed + " km/h\n";
        statsHud.text += "Altitude: " + currentAlt;
        titleHud.text = "Objective: Collect All Dino Eggs!\nRemaining Eggs: " + (maxEggs - eggsCollected);

        timer = System.TimeSpan.FromSeconds(activeTimer);
        timerHUD.text = "Your Time: " + timer.ToString("hh':'mm':'ss") + "\nTime To Beat: " + rtime.ToString("hh':'mm':'ss");
    }

    public void Liftoff()
    {
        landingCollider.SetActive(false);
        for (int i = 0; i < collArr.Length; i++) collArr[i].enabled = true;
        rb.AddForce(Vector3.up * 15, ForceMode.VelocityChange);
    }
    public void Flap()
    {
        mainAud.volume = 0.25f;
        mainAud.PlayOneShot(flapAudio[Random.Range(0, flapAudio.Length)]);
    }
    public void LandingAnim()
    {
        landingCollider.SetActive(true);
        for (int i = 0; i < collArr.Length; i++) collArr[i].enabled = false;

        animator.SetBool("isFlying", false);
        animator.SetBool("isFlapping", false);
        rb.velocity = Vector3.zero;
    }
    public void TakeoffAnim()
    {
        animator.SetBool("isFlying", true);
        animator.SetBool("isFlapping", true);
        //rb.constraints = RigidbodyConstraints.None;
    }
    public void GameOver()
    {
        float highScore = PlayerPrefs.GetFloat("BestTime", 10000.0f);
        GameOverMenu.SetActive(true);
        playerTime.text = timer.ToString("hh':'mm':'ss");
        if (highScore > activeTimer)
        {
            isWinnerText.text = "Wow! What a PTERRIFIC score!\nYou're the Ptop Dog now!";
            PlayerPrefs.SetFloat("BestTime", activeTimer);
            rtime = System.TimeSpan.FromSeconds(PlayerPrefs.GetFloat("BestTime", 12345.0f));
        }
        else
        {
            isWinnerText.text = "Wow! What a PTERRIBLE score!\nYou need to PTOUCH UP on your flying!";
        }
        secAud.volume = 0.25f;
        secAud.loop = true;
        secAud.clip = winnerMusic;
        secAud.Play();
        bestTime.text = rtime.ToString("hh':'mm':'ss");
        Time.timeScale = 0;
    }
}
